version: '3.5'
services:
  api1: # API - Instância 01
    image: guigomesa/guigomesa.rinhabackend:latest
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__RinhaContext=Host=db;Port=5432;Database=rinha;Username=guigo;Password=rinha123
    hostname: api1
    depends_on:
      - db
    expose:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.625GB'
  api2: # API - Instância 01
    image: guigomesa/guigomesa.rinhabackend:latest
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__RinhaContext=Host=db;Port=5432;Database=rinha;Username=guigo;Password=rinha123
    hostname: api2
    depends_on:
      - db
    expose:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.625GB'
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./config/ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.25GB'
  db: # Banco de dados
   image: postgres
   hostname: db
   environment:
    - POSTGRES_PASSWORD=rinha123
    - POSTGRES_USER=guigo
    - POSTGRES_DB=rinha
   volumes:
    - ./config/script.sql:/docker-entrypoint-initdb.d/ddl.sql
   deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '1GB'
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '.5GB'
networks:
  default:
    driver: bridge
    name: rinha
  