version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: guigo
      POSTGRES_PASSWORD: rinha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
