version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:7.0
    volumes:
         - ../..:/workspaces:cached
    network_mode: service:rabbit
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: guigo
      POSTGRES_PASSWORD: rinha123
volumes:
  postgres-data: