version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:7.0
    volumes:
         - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: "host"
    ports:
      - "5000:5000"
      - "5001:5001"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: guigo
      POSTGRES_PASSWORD: rinha123
      network_mode: "host"
volumes:
  postgres-data: